---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-server-pvc
  namespace: nextcloud
spec:
  storageClassName: "longhorn" 
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 64Gi
