apiVersion: v1
kind: Secret
metadata:
  name: nextcloud-db-secret
  namespace: nextcloud
  annotations:
    reflector.v1.k8s.emberstack.com/reflection-allowed: "true" #using reflector to mirror secrets to other namespace
    reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "default,kube-system,nextcloud" 
type: Opaque
data:
  MYSQL_DATABASE: bmV4dGNsb3Vk #echo -n 'nextcloud' | base64
  MYSQL_USER: bmV4dGNsb3Vk
  MYSQL_PASSWORD: ${SecretPassword} #your secretpassword here
  MYSQL_ROOT_PASSWORD: ${SecretPassword}
